ThumbnailerManager: No need to get the string from resources more than once
This may fix the following crash:

java.lang.IllegalStateException: Fragment VideoListFragment{4130f1f0} not attached to Activity
at android.support.v4.app.Fragment.getResources(Fragment.java:555)
at org.videolan.vlc.betav7neon.ThumbnailerManager.run(ThumbnailerManager.java:113)
at java.lang.Thread.run(Thread.java:856)