BitmapCache: don't return a recycled bitmap from the cache
Android tends to recycle bitmaps automatically when a view is destroyed
regardless of whether it is still being used somewhere else. And that
can lead to a crash of this kind:
    RuntimeException: Canvas: trying to use a recycled bitmap