respect fragment's lifecycle
this should fix this error :
java.lang.RuntimeException: Unable to destroy activity
...
Caused by: java.lang.IllegalArgumentException: Receiver not registered: